#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Trackmind
# SPDX-License-Identifier: MIT
# sdlc-atlas one-shot setup: platform + project + stack [+ org] in one command.
#
#   bash setup-all.sh --project /c/dev/todo-api --stacks fastapi,react --layer todo
#   bash setup-all.sh --project /c/dev/acme-api --stack fastapi --layer acme
#   bash setup-all.sh --project /c/dev/myrepo --stack python [--org /c/dev/org-policy]
#
# --layer <name>: use projects/<name>/ if it exists, else create it from template first.
#
# Structure after setup:
#   $HOME/.claude/stacks/<name>/agents/<agent>/AGENT.md   ← stack layer (subfolder per agent)
#   $HOME/.claude/stacks/<name>/skills/<skill>/SKILL.md   ← stack layer (subfolder per skill)
#   <project>/.claude/agents/<agent>.md                   ← project layer (flat)
#   <project>/.claude/skills/<skill>.md                   ← project layer (flat)
set -euo pipefail
SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJ="" STACK="" ORG="" LAYER="" PROFILE="standard"
while [ $# -gt 0 ]; do case "$1" in
  --project) PROJ="$2"; shift 2;;
  --stack|--stacks) STACK="$2"; shift 2;;
  --org)     ORG="$2"; shift 2;;
  --layer)   LAYER="$2"; shift 2;;
  --profile) PROFILE="$2"; shift 2;;
  *) echo "unknown arg $1"; exit 1;;
esac; done
[ -n "$PROJ" ] || { echo "required: --project <repo path>"; exit 1; }
# a path already ending in a layer dir would nest it (.claude/.claude) - use the parent
bs=$(printf '\134'); PROJ="${PROJ//"$bs"//}"; PROJ="${PROJ%/}"
case "$PROJ" in
  .claude|.cursor) PROJ=".." ;;
  */.claude|*/.cursor) echo "    --project ends in a layer dir - using its parent"; PROJ="${PROJ%/*}" ;;
esac

echo "==> [1/6] Platform layer -> ~/.claude"
echo "    Stack agents/skills installed as subfolders: agents/<name>/AGENT.md, skills/<name>/SKILL.md"
bash "$SRC/install.sh" --platform

echo "==> [2/6] Project layer -> $PROJ/.claude"
if [ -d "$PROJ/.claude" ]; then
  echo "    .claude exists - keeping it (no overwrite)."
elif [ -n "$LAYER" ]; then
  [ -n "$STACK" ] || { echo "    --layer requires --stack or --stacks (e.g. --stacks fastapi,react)"; exit 1; }
  bash "$SRC/install.sh" --init-layer "$LAYER" --stacks "$STACK" --profile "$PROFILE"
  bash "$SRC/install.sh" --project-layer "$LAYER" --project "$PROJ"
else
  bash "$SRC/install.sh" --new-project "$PROJ"
fi

# Stamp profile and primary stack into CLAUDE.md so the doctor passes without /audit-project.
#
# projects/project-template/ deliberately ships no CLAUDE.md — the full file is generated by
# /audit-project, which fills all 28 {{PLACEHOLDER}} values from the real repo. But this
# block used to be guarded by `[ -f "$CLAUDE_MD" ]` alone, so with no template file it
# silently did nothing and step [6/6] Doctor then failed every run with "missing CLAUDE.md".
# Seed a minimal-but-valid file instead: enough for the doctor and the orchestrator to read
# identity, profile, stack, and gate commands, with /audit-project still the way to get the
# full version.
CLAUDE_MD="$PROJ/.claude/CLAUDE.md"
PRIMARY_STACK="${STACK%%,*}"   # first stack before any comma
if [ -f "$CLAUDE_MD" ]; then
  sed -i "s/{{PROFILE}}/$PROFILE/g" "$CLAUDE_MD"
  sed -i "s/{{STACK_PRIMARY}}/$PRIMARY_STACK/g" "$CLAUDE_MD"
  echo "    Stamped profile=$PROFILE stack=$PRIMARY_STACK into CLAUDE.md"
else
  PROJ_NAME="$(basename "$PROJ")"
  # Gate commands come from the stack's own STACK.md, the same source
  # tools/init-project-layer.sh reads, so a project and its stack cannot disagree.
  sd() { # $1 = stack slug, $2 = field
    [ -n "$1" ] && [ -f "$SRC/stacks/$1/STACK.md" ] || return 0
    grep -m1 -oE "$2 \`[^\`]+\`" "$SRC/stacks/$1/STACK.md" 2>/dev/null \
      | head -1 | sed -E "s/^$2 \`//; s/\`$//" || true
  }
  {
    echo "# ${PROJ_NAME} — Project Layer (L3)"
    echo "profile: ${PROFILE}"
    echo "stack: ${STACK:-none}"
    echo "tech_leads: [FILL IN — who may /approve-proposal at project layer]"
    echo ""
    echo "## Issue tracker"
    echo "tracker: github"
    echo "github_repo: [FILL IN owner/repo — or remove if you use no tracker]"
    echo ""
    echo "## Commands the gates run"
    echo "test: $(sd "$PRIMARY_STACK" test)"
    echo "security: $(sd "$PRIMARY_STACK" security)"
    echo "lint: $(sd "$PRIMARY_STACK" lint)"
    echo ""
    echo "## Conventions (hard rules a coding agent must never violate)"
    echo "- [FILL IN domain-specific rules for ${PROJ_NAME}]"
    echo ""
    echo "> Seeded by setup-all.sh. Run /audit-project to replace this with a full"
    echo "> CLAUDE.md generated from the actual repository."
  } > "$CLAUDE_MD"
  echo "    Seeded CLAUDE.md (profile=$PROFILE stack=${STACK:-none}) — run /audit-project to complete it"
fi

if [ -n "$STACK" ]; then
  echo "==> [3/6] Stack(s) '$STACK' merge"
  echo "    Stack agents/skills grouped by stack name: agents/<stack>/<name>/AGENT.md, skills/<stack>/<name>/SKILL.md"
  if [[ "$STACK" == *","* ]]; then
    bash "$SRC/install.sh" --stacks "$STACK" --project "$PROJ"
  else
    bash "$SRC/install.sh" --stack "$STACK" --project "$PROJ"
  fi
else echo "==> [3/6] No --stack given - skipped"; fi

if [ -n "$ORG" ]; then
  echo "==> [4/6] Org policy merge"; bash "$SRC/install.sh" --org "$ORG" --project "$PROJ"
else echo "==> [4/6] No --org given - skipped (fine for minimal/standard)"; fi

echo "==> [5/6] .gitignore"
[ -f "$PROJ/.claude/gitignore-template" ] && mv -f "$PROJ/.claude/gitignore-template" "$PROJ/.claude/.gitignore" && echo "    gitignore-template -> .gitignore"
[ -f "$PROJ/.claude/knowledge.md" ] && [ ! -f "$PROJ/knowledge.md" ] && mv "$PROJ/.claude/knowledge.md" "$PROJ/knowledge.md" && echo "    knowledge.md moved to repo root"

echo "==> [6/6] Doctor"
if bash "$SRC/install.sh" --doctor "$PROJ"; then
  echo
  echo "Structure summary:"
  echo "  Platform:  $HOME/.claude/stacks/<stack>/agents/<name>/AGENT.md"
  echo "             $HOME/.claude/stacks/<stack>/skills/<name>/SKILL.md"
  echo "  Project:   $PROJ/.claude/agents/<stack>/<name>/AGENT.md"
  echo "             $PROJ/.claude/skills/<stack>/<name>/SKILL.md"
  echo
  if [ -n "$LAYER" ]; then
    echo "DONE. Layer: projects/$LAYER -> $PROJ/.claude"
  else
    echo "DONE. Open Claude Code in $PROJ and run /feature #<story>"
  fi
else
  echo
  echo "ALMOST DONE - fix the warnings above (usually: fill [FILL IN] in $PROJ/.claude/CLAUDE.md), then re-run:"
  echo "  bash $SRC/install.sh --doctor $PROJ"
fi
